[project]
name = "fiafcore-bfi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.0",
    "pandas>=2.3.3",
    "pyarrow>=21.0.0",
    "rdflib==7.1.3",
    "tqdm>=4.67.1",
]
